### ISSUE TITLE
브랜치 전략은?

### ISSUE THREAD

**Issue by jordy-torvalds** [jordy-with-friends/round-table#1]
디벨롭 마스터 머지시 배포와 같이 이미 개요는 잡혔으나 프로젝트를 위해서는 구체화 및 확정이 필요하다고 생각합니다!

**Comment by lkimilhol** [comment]
프로젝트 소스코드 레포를 https://github.com/jordy-with-friends/jordy-shop에 만들었는데요.
이 프로젝트를 각자 fork를 하고, fork->공용 repo로 풀리퀘스트를 날리도록 하면 어떨까요?

**Comment by jordy-torvalds** [comment]
1. master에서 branch 생성($assignee/$issue-sequence)
2. developing...
3. master pull
4. PR
5. local syncing..
6. MERGE
