### ISSUE TITLE
어떤 도메인을 먼저 개발해볼까요?

### ISSUE THREAD

**Issue by lkimilhol** [jordy-with-friends/round-table#11]
회원, 주문 등등의 도메인을 개발해야 할텐데, 회원부터 하면 좋을까요? (통상 그렇게들 하는거같아서...)

하게 된다면 어떤식으로 개발을 나눠서 하면 좋을지 논의해봅시당 :)

**Comment by jordy-torvalds** [comment]
회원부터 진행!!

## 룰

1. 이슈 / 티켓 / 할당
2. 회원부터 진행!
3. 카톡으로는 계속 협의
4. 공식적인 회의는 매주 혹은 최소 2주에 한 번은 무조건
