### ISSUE TITLE
회원 이메일 인증의 임시 테이블을 어떻게 사용할까?

### ISSUE THREAD

**Issue by lkimilhol** [jordy-with-friends/round-table#17]
1. 일단 관리의 용이함을 위하여 db를 계속 이용.
2. 나중에 수정할 필요가 있을것으로 예상되니 처음부터 redis를 이용

**Comment by jordy-torvalds** [comment]
EHCACHE 갑시드아~

**Comment by lkimilhol** [comment]
1. 로컬 캐시를 사용할 수 있을거같다. -> 로컬에 저장하면 공유가 되지 않으니 레디스를 사용하자는 의견이 나옴
2. rds 저장하는 것도 방법 일 수 있을거 같다.
3. 로컬 캐시를 일단 사용하고 레디스로 마이그레이션을 하자.
4. ehcache를 사용하자. 추후에 바로 교체가 가능하기 때문이다! (Spring Cache를 적용하고 나중에 redis로 교체 필요할 때 이용하자!)

-> 4번 결정
