### ISSUE TITLE
어떤 도메인으로 프로젝트를 진행할 것인가?

### ISSUE THREAD

**Issue by jordy-torvalds** [jordy-with-friends/round-table#2]

**Comment by lkimilhol** [comment]
이커머스 기준으로 시작을 하되, 하나의 도메인에 집중하면서 서서히 늘리면 어떨까요?
말씀하셨던거 처럼 구체화는 반드시 필요해보입니다만, 구체화를 하다가 프로젝트 시작도 못하고 펑 하면 안되니, 간단하게 회원 부터 시작해서 필요로 하는 도메인을 하나하나 추가하다가, 뭔가 다른 도메인에 도전하고 싶다면 그 때 방향을 살짝 틀어서 모두가 하고싶은 도메인을 개발해보면 다들 만족스러울거같아요.

저는 일단 시작부터 하나하나 했음 합니다 ㅎㅎ

**Comment by jordy-torvalds** [comment]
1. 레퍼런스: 배달의민족
2. 배달만!
3. 배달 메뉴 내 우선순위 정하기
4. *** 멀티 모듈 ***, 어그리게이트 루트
![image](https://user-images.githubusercontent.com/58139899/132093573-e999de03-8e70-4eec-af48-0424ee257ac6.png)
