### ISSUE TITLE
UI는 어떻게 할 것인가?

### ISSUE THREAD

**Issue by jordy-torvalds** [jordy-with-friends/round-table#3]

**Comment by lkimilhol** [comment]
포스트맨으로 시작하고, 간단하게 소스코드 복붙으로 타임리프를 해도 괜찮을거같아요.
개인적으로 누군가가 프론트쪽 욕심이 있다면 개발해 보는것도 좋을듯 합니다 ㅎㅎ (전 아님)

**Comment by bbbnam** [comment]
일단 작업하고 프론트쪽이 꼭 필요하다~?
혹은 이걸 진짜 뭐 사업으로 해봐야겠다? 등의 요구치가 커진다거나 하면
제가 우리 회사 퍼블 분께 부탁드려 보겠습니다. ㅋㅋㅋ

**Comment by jordy-torvalds** [comment]
담당자가 책임지고 http 파일 개발하고 UI는 하지맙시다!
