### ISSUE TITLE
로컬 캐시도 사용할 것인가? 사용할 라이브러리의 종류는?

### ISSUE THREAD

**Issue by jordy-torvalds** [jordy-with-friends/round-table#5]

**Comment by lkimilhol** [comment]
제 생각으론 일단 mysql 기준으로 진행하고, 우리가 트래픽은 없지만 이 정도는 로컬캐시를 사용하자 싶으면 그 때 라이브러리를 정하면 어떨까요?
우리가 필요로 하는 캐시는 그 때 가서 결정 할 수 있을거같아요.

**Comment by jordy-torvalds** [comment]
도메인 정의 시점에 필요하면 어떤걸 사용할지 확정 및 도입!

도메인 정의 선행 필요!
