### ISSUE TITLE
시크릿, 키, 아이디, 패스워드 등에 대한 관리는?

### ISSUE THREAD

**Issue by jordy-torvalds** [jordy-with-friends/round-table#6]

**Comment by lkimilhol** [comment]
음 이건 고민해봐야겠군요. aws를 파게 된다면 어떻게 할지 고민해봐야할거같습니다.

**Comment by jordy-torvalds** [comment]
쿄님 의견: AWS HASHICORP VAULT

**Comment by jordy-torvalds** [comment]
## 참고자료
1. https://spring.io/projects/spring-vault#samples
2. https://spring.io/projects/spring-cloud-vault
3. https://aws.amazon.com/ko/quickstart/architecture/vault/
