### ISSUE TITLE
beanstalk vs (auto scailing & code deploy) ?

### ISSUE THREAD

**Issue by bbbnam** [jordy-with-friends/round-table#9]
우형 기술블로그를 보니
https://techblog.woowahan.com/2587/

beanstalk은 자동화 측면에서 좋은데
단점이 여러 서버에 배포할 때 그 중 한개 서버에만 다른 설정을 주고자 할 때
어렵다는 점을 들어
auto scailing & code deploy
이 방식으로 변경하였다 하는데,
저희도 일단 beanstalk으로 진행 후에 추후에 변경해 보는 것으로 할까요?

아니면 시작부터 후자로 할까요?

**Comment by jordy-torvalds** [comment]
흥돋 글 감사합니다. 미리 읽어 둘게요!

**Comment by jordy-torvalds** [comment]
전에 CI·CD 공부할 때 빈스토크로 실습했는데, 이 때 부트 속도가 너무 느려서 숨막혔던 기억이 떠오르네요 ㅋㅋ
1분마다 커밋 푸쉬를 하지는 않겠지만, 좀 더 기민한 적용을 위해 최초부터 auto scailing & code deploy를 택하고 싶네요!
(가주아!!!)

**Comment by jordy-torvalds** [comment]
![image](https://user-images.githubusercontent.com/58139899/131603927-fe378e21-ec4e-464d-b7f8-f007a7b02831.png)
특정 벤더에 묶이면 안된다고 했는데 ㅋㅋㅋㅋ 왜 SPRING CLOUD AWS의 어노태이션을 썻는지 이해가 안되네요 ..ㅠ
(https://techblog.woowahan.com/2587/ 의 1.2.의 내용 입니다.)

**Comment by lkimilhol** [comment]
CI CD에 전무하지만 내용을 좀 보다보니 고민이 되네요. 이건 조금 더 고민해보겠습니다.

**Comment by jordy-torvalds** [comment]
굳이 한 대의 서버를 쓸 것인데 코드 디플로이를 써가며 시간을 쓸 필요가 없다.

실제 중요한 비즈니스 로직, 도메인에 집중하기 위해 자동화된 인프라인 빈스토크를 선택하고,

향후 젠킨스와의 연동 등에 있어 불편함이 있을 경우 아키텍처에 대한 고민은 다시 한다.
